### ISSUE TITLE
Undefined activity bug

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1308]
```
2015/03/19 16:04:56 [error] 3076#0: *8497 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Target must be larg
er than current value.' in /var/www/runalyze/user/inc/core/Model/Loop.php:166
Stack trace:
#0 inc/core/Model/Trackdata/Loop.php(91): Runalyze\Model\Loop->moveTo('distance', 26)
#1 inc/core/Data/Laps/Calculator.php(113): Runalyze\Model\Trackdata\Loop->moveToDistance(26)
#2 inc/core/Data/Laps/Calculator.php(68): Runalyze\Data\Laps\Calculator->move(26)
#3 inc/core/Data/Laps/Laps.php(33): Runalyze\Data\Laps\Calculator->calculateFrom(Object(Runalyze\Model\Trackdata\Object), Object(Runalyze\Model\Route\Obje
ct))
#4 inc/training/view/section/table/class.TableLapsComputed.php(42): Runalyze\Data\Laps\Laps->calculateFrom(Array, Object(Runalyze\Model\Trackdata\Object),
 Object(Runalyze\Model\Route\Object))
#5 inc/training/view/section/table/class.TableLapsComputed.php(27): T" while reading response header from upstream, client:*.*.*.*, server: user.runalyze.de, request: "GET /call/call.Training.display.php?id=527194 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "*", referrer: "*"
```

Trainingsid = 527194

**Comment by laufhannes** [comment]
There were a lot of such errors - but so far nobody complained. I can't see anything special about that activity so far ...

**Comment by laufhannes** [comment]
Ah, I found it:
```
...|24.52173|26.57001|...
```

There is no datapoint for kilometer 25, thus `move(25)` moves to 26.57 and `move(26)` fails.
