### ISSUE TITLE
Processing activity error (array mismatch - elevations_original))

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1342]
Files are in our teamfolder
````
2015/03/28 16:44:25 [error] 30074#0: *25340 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Data arrays must be of the same size. (3086 != 1) (for elevations_original)' in /var/www/runalyze/user/inc/core/Model/Route/Object.php:170
Stack trace:
#0 /var/www/runalyze/user/inc/core/Model/Route/Object.php(151): Runalyze\Model\Route\Object->checkArraySizes()
#1 /var/www/runalyze/user/inc/training/class.TrainingObject.php(189): Runalyze\Model\Route\Object->__construct(Array)
#2 /var/www/runalyze/user/inc/training/class.TrainingObject.php(138): TrainingObject->newRouteObject()
#3 /var/www/runalyze/user/inc/html/formular/class.StandardFormular.php(98): TrainingObject->insert()
#4 /var/www/runalyze/user/inc/html/formular/class.StandardFormular.php(72): StandardFormular->checkForSubmit()
#5 /var/www/runalyze/user/inc/html/formular/class.StandardFormular.php(53): StandardFormular->init(Object(TrainingObject))
#6 /var/www/runalyze/user/inc/import/class.ImporterWindowTabFormular.php(63): StandardFormular->__construct(Object(Tra" while reading response header from upstream, client:****, server: user.runalyze.de, request: "POST /call/call.Training.create.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "", referrer: "/index.php""
````

**Comment by laufhannes** [comment]
Seems that this is the same problem as in #1375 and thus fixed since 8f375cb.
