### ISSUE TITLE
Registration of new users fails

### ISSUE THREAD

**Issue by winnieXY** [Runalyze/Runalyze#1536]
I've tried to setup a brand new runalyze instance using the git tag v2.1.0.

Everyting seems to work okay, however I can't register any user (actually I can, but the registration email is not sended out because of an SQL Syntax error). 

The error which pops up in error.log is:
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1' at line 1' in /srv/runalyze-git/inc/system/class.PDOforRunalyze.php:259
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: Stack trace:
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #0 /srv/runalyze-git/inc/system/class.PDOforRunalyze.php(259): PDO->query('SELECT * FROM `...')
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #1 /srv/runalyze-git/inc/system/class.PDOforRunalyze.php(85): PDOforRunalyze->query('SELECT * FROM `...')
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #2 /srv/runalyze-git/inc/system/class.AccountHandler.php(477): PDOforRunalyze->fetchByID('account', '2')
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #3 /srv/runalyze-git/inc/system/class.AccountHandler.php(261): AccountHandler::setAndSendActivationKeyFor('2', Array)
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #4 /srv/runalyze-git/inc/system/class.AccountHandler.php(222): AccountHandler::createNewUserFromPost()
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #5 /srv/runalyze-git/inc/tpl/tpl.loginWindow.php(63): AccountHandler::tryToRegisterNewUser()
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #6 /srv/runalyze-git/login.php(39): include('/srv/runalyze-g...')
2015-10-21 06:15:51: (mod_fastcgi.c.2695) FastCGI-stderr: #7 { in /srv/runalyze-git/inc/system/class.PDOforRunalyze.php on line 259

Deleting manually the activation code from mysql make it possible to use this user.

Greetings
Patrick

**Comment by mipapo** [comment]
I think in the git tag we missed that fix. But it's fixed in the official release and it's fixed in the version coming up this weekend.

**Comment by laufhannes** [comment]
I just realized that we still haven't released v2.1.1. This bug is fixed in our `support/2.1.x` branch, see d7503f0beede611bfc7f3f4de246265fdc40dbdf.
