### ISSUE TITLE
Uninstall plugin doesn't work

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1637]
````
  thrown in /var/www/runalyze/user/inc/system/class.PDOforRunalyze.php on line 268" while reading response header from upstream, client: 217.162.221.196, server: runalyze.com, request: "GET /call/call.Plugin.uninstall.php?key=RunalyzePlug
inStat_Trainingspartner HTTP/1.1", upstream: "fastcgi://unix:/var/run/runalyzecom.sock:", host: "runalyze.com", referrer: "https://runalyze.com/"
2015/12/16 07:15:31 [error] 7521#0: *213632 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accountid' in 'where clause'' in /
var/www/runalyze/user/inc/system/class.PDOforRunalyze.php:268
Stack trace:
#0 /var/www/runalyze/user/inc/system/class.PDOforRunalyze.php(268): PDO->query('DELETE FROM `ru...')
#1 /var/www/runalyze/user/inc/plugin/class.PluginInstaller.php(79): PDOforRunalyze->query('DELETE FROM `ru...')
#2 /var/www/runalyze/user/call/call.Plugin.uninstall.php(15): PluginInstaller->uninstall()
#3 {main}
  thrown in /var/www/runalyze/user/inc/system/class.PDOforRunalyze.php on line 268" while reading response header from upstream, client: , server: runalyze.com, request: "GET /call/call.Plugin.uninstall.php?key=RunalyzePlug
inStat_Trainingspartner HTTP/1.1", upstream: "fastcgi://unix:/var/run/runalyzecom.sock:", host: "runalyze.com", referrer: "https://runalyze.com/"
````

**Comment by laufhannes** [comment]
This does not work for 2.3.x either.

**Comment by laufhannes** [comment]
As InnoDB is recommended, data from `runalyze_plugin_conf` should be deleted automatically.
