### ISSUE TITLE
sending registration mail fails due to uncaught exception 'PDOException' Table 'runalyze_equipment_type' doesn't exist

### ISSUE THREAD

**Issue by Strubbl** [Runalyze/Runalyze#1729]
Hi,
i am running a fresh instance of runalyze 2.4. And after a new user registration i see the following error in the apache log:

```
[Sun Jan 31 18:39:23.102018 2016] [:error] [pid 10157] [client 95...8:38226] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 
1146 Table 'runalyze.prod_runalyze_equipment_type' doesn't exist' 
in /var/www/runalyze/inc/system/class.PDOforRunalyze.php:268\n
Stack trace:\n
#0 /var/www/runalyze/inc/system/class.PDOforRunalyze.php(268): PDO->query('INSERT INTO `pr...')\n
#1 /var/www/runalyze/inc/system/class.PDOforRunalyze.php(168): PDOforRunalyze->query('INSERT INTO `pr...')\n
#2 /var/www/runalyze/inc/system/class.AccountHandler.php(437): PDOforRunalyze->insert('runalyze_equipm...', Array, Array)\n
#3 /var/www/runalyze/inc/system/class.AccountHandler.php(239): AccountHandler::importEmptyValuesFor('5')\n
#4 /var/www/runalyze/inc/system/class.AccountHandler.php(210): AccountHandler::createNewUserFromPost()\n
#5 /var/www/runalyze/inc/tpl/tpl.loginWindow.php(63): AccountHandler::tryToRegisterNewUser()\n
#6 /var/www/runalyze/login.php(39): include('/var/www/runaly...')\n
#7 {main}\n  
thrown in /var/www/runalyze/inc/system/class.PDOforRunalyze.php on line 268, referer: https://run..de/login.php
```

Due to this error no activation mails are sent. 
I have the table prod_equipment_type but not the table prod_runalyze_equipment_type. So my table prefix might have caused that problem.

**Comment by mipapo** [comment]
The table should exists. 
This is a bug in 2.4 if you're using another prefix.
Have a look at:
https://github.com/Runalyze/Runalyze/commit/8d9db2ace8108a5ba65cfae197617f20007679b9
And change the file as shown. We will release a bugfix release soon.

**Comment by Strubbl** [comment]
Thanks!
