### ISSUE TITLE
Logbook import fails due to non-numeric activity ids

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1731]
```
Uncaught exception 'InvalidArgumentException' with message 'All activity ids must be numerical.' in .../inc/core/Activity/DuplicateFinder.php:63
Stack trace:
#0 .../inc/import/class.MultiImporterFormular.php(77): Runalyze\Activity\DuplicateFinder->checkForDuplicates(Array)
#1 .../inc/import/class.MultiImporterFormular.php(59): MultiImporterFormular->getFieldsetBlock()
#2 .../inc/import/class.MultiImporterFormular.php(51): MultiImporterFormular->initForObjects()
#3 .../inc/import/class.ImporterWindowTabFormular.php(74): MultiImporterFormular->setObjects(Array)
#4 .../inc/import/class.ImporterWindowTabFormular.php(52): ImporterWindowTabFormular->displayMultipleFormular()
#5 .../inc/import/class.ImporterWindowTab.php(55): ImporterWindowTabFormular->displayTab()
```

**Comment by laufhannes** [comment]
Activity id seems to be null for these activities. `DuplicateFinder` should accept `null` values as activity ids and ignore them for the query (but correctly return `false` for them).
