### ISSUE TITLE
Garmin Communicator - import fails due to activity matcher

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1773]
````
 [error] 17076#0: *199132 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Given timestamp must be numeric.' in /var/www/runalyze/user/inc/core/Util/LocalTime.php:58
Stack trace:
#0 /var/www/runalyze/user/call/ajax.activityMatcher.php(23): Runalyze\Util\LocalTime::fromServerTime(false)
#1 /var/www/runalyze/user/call/ajax.activityMatcher.php(41): parserStrtotime('31Z')
#2 [internal function]: {closure}('31Z')
#3 /var/www/runalyze/user/call/ajax.activityMatcher.php(42): array_map(Object(Closure), Array)
#4 {main}
  thrown in /var/www/runalyze/user/inc/core/Util/LocalTime.php on line 58" while reading response header from upstream, client: , server:, request: "POST /call/ajax.activityMatcher.php, referrer: "https://runalyze.com/call/call.garminCommunicator.php"
````

**Comment by mipapo** [comment]
mh...Well I just tested it with a Garmin 220 and the ID, which was forwarded to the activityMatcher was fine:
PHP message: matcher2015-09-07T13:32:29Z
PHP message: matcherID2015-09-07T06:33:59Z

**Comment by laufhannes** [comment]
Using `(int)strtotime` in https://github.com/Runalyze/Runalyze/blob/master/call/ajax.activityMatcher.php#L23 should fix it anyhow.  We shouldn't rely on the Garmin Communicator to serve valid IDs (i.e. date time strings).
