### ISSUE TITLE
Race result remains in cache after deletion

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1840]
As `RaceResult\Deleter` does not extend `DeleterWithIDAndAccountID`, this is not done automatically so far.

**Comment by laufhannes** [comment]
Okay, the cache is not the problem. But then I don't know how this message can occur:
```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'XXX' for key 'PRIMARY'' in /runalyze/inc/system/class.PDOforRunalyze.php:256
Stack trace:
#0 /runalyze/inc/system/class.PDOforRunalyze.php(256): PDO->exec('\n\t\t\tINSERT INTO...')
#1 /runalyze/inc/core/Model/Inserter.php(141): PDOforRunalyze->exec('\n\t\t\tINSERT INTO...')
#2 /runalyze/inc/core/Model/Inserter.php(102): Runalyze\Model\Inserter->runManualInsert()
#3 /runalyze/inc/core/Model/Inserter.php(91): Runalyze\Model\Inserter->runInsert()
#4 /runalyze/inc/training/class.TrainingFormular.php(177): Runalyze\Model\Inserter->insert()
#5 /runalyze/inc/training/class.TrainingFormular.php(158): TrainingFormular->insertRaceResult()
#6 /runalyze/inc/training/class.TrainingFormular.php(114): TrainingFormular->handleRaceResultCheckbox()
while reading response header from upstream, request: "POST /call/call.Training.edit.php"
```

**Comment by laufhannes** [comment]
Adding and deleting a race result two times produces this error. The problem: The inserter does not clear the cache (which still holds an empty array after deleting the result).
