### ISSUE TITLE
Routemap - NULL values

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1866]
Not sure why there are NULL values - But there is definitely something wrong
```
2016/06/23 13:02:11 [error] 3852#3852: *1799044 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught League\Geotools\Exception\InvalidArgumentException: The geo hash should be a string. in /var/www/runalyze/production/htdocs/vendor/league/geotools/src/Geohash/Geohash.php:182
Stack trace:
#0 /var/www/runalyze/production/htdocs/plugin/RunalyzePluginStat_Strecken/window.routenet.php(71): League\Geotools\Geohash\Geohash->decode(NULL)
#1 {main}
  thrown in /var/www/runalyze/production/htdocs/vendor/league/geotools/src/Geohash/Geohash.php on line 182" while reading response header from upstream, client: , server: runalyze.com, request: "GET /plugin/RunalyzePluginStat_Strecken/window.routenet.php?sport=38188&y=2013 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm-runalyze.sock:", host: "runalyze.com", referrer: "https://runalyze.com/index.php"
2016/06/23 13:02:44 [error] 3852#3852: *1799044 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught League\Geotools\Exception\InvalidArgumentException: The geo hash should be a string. in /var/www/runalyze/production/htdocs/vendor/league/geotools/src/Geohash/Geohash.php:182
Stack trace:
#0 /var/www/runalyze/production/htdocs/plugin/RunalyzePluginStat_Strecken/window.routenet.php(71): League\Geotools\Geohash\Geohash->decode(NULL)
#1 {main}
  thrown in /var/www/runalyze/production/htdocs/vendor/league/geotools/src/Geohash/Geohash.php on line 182" while reading response header from upstream, client:  server: runalyze.com, request: "GET /plugin/RunalyzePluginStat_Strecken/window.routenet.php?sport=38188&y=2013 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm-runalyze.sock:", host: "runalyze.com", referrer: "https://runalyze.com/index.php"
```

**Comment by laufhannes** [comment]
That are obviously values from an earlier version and could be fixed with `build/global.routefix.php` (which may be removed in v3.0).

I'll fix the route net, but there may be other parts of the code that may fail due to this screwed route fields.
