### ISSUE TITLE
DB password seems too complex for logging in

### ISSUE THREAD

**Issue by rob-st** [Runalyze/Runalyze#1923]
Today I upgraded my self hosted version to runalyze 3.0.0 (using the downloadable ZIP). After some tracing and a lot of help of the @runalyze twitterer, I came up with the "*bug*" of my database password being to complex.

## Environment
PHP 5.5.38
MySQL Server: Localhost via UNIX socket
Server-Typ: MySQL
Server Version: 5.6.26-cll-lve - MySQL Community Server (GPL)
Protokoll-Version: 10
Server Zeichensatz: UTF-8 Unicode (utf8)

Database password **was**: `9(G9V22i33{3y32[%%2w` - since it didn't work, I had to change it anyway.

## Detection
Actually the bug was not that easy to find. The runalyze login page was rejecting my login, telling me 

> Die Authentifikation konnte wegen eines Systemproblems nicht bearbeitet werden.

The shared trainings and public training log were accessible though. So at first there was no point that led to the idea of having an issue with the database.

I used advanced error reporting (debug-mode in `app/config/config.yml`) and my apache error log to get these error messages:

### symfony.log:
    [2016-08-29 11:57:51] request.INFO: Matched route "{route}". {"route":"login_check","route_parameters":{"_controller":"Runalyze\\Bundle\\CoreBundle\\Controller\\DefaultController::loginCheckAction","_locale":"de","_route":"login_check"},"request_uri":"http://runalyze.kellerclub.eu/de/login_check","method":"POST"} []
	[2016-08-29 11:57:51] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'kellercl_runalyz'@'localhost' (using password: YES) at /home/kellercl/public_html/runalyze/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:94, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'kellercl_runalyz'@'localhost' (using password: YES) at /home/kellercl/public_html/runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'kellercl_runalyz'@'localhost' (using password: YES) at /home/kellercl/public_html/runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'kellercl_runalyz'@'localhost' (using password: YES) at /home/kellercl/public_html/runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
	[2016-08-29 11:57:51] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
	[2016-08-29 11:57:51] request.INFO: Matched route "{route}". {"route":"login","route_parameters":{"_controller":"Runalyze\\Bundle\\CoreBundle\\Controller\\DefaultController::loginAction","_locale":"de","_route":"login"},"request_uri":"http://runalyze.kellerclub.eu/de/login","method":"GET"} []
	[2016-08-29 11:57:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
	[2016-08-29 11:57:51] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Yaml\Exception\ParseException: "Found unknown escape character "\(" at line 8 (near "database_password: "9\(G9V22i33\{3y32\[\%\%2w"")." at /home/kellercl/public_html/runalyze/vendor/symfony/symfony/src/Symfony/Component/Yaml/Unescaper.php line 117 {"exception":"[object] (Symfony\\Component\\Yaml\\Exception\\ParseException(code: 0): Found unknown escape character \"\\(\" at line 8 (near \"database_password: \"9\\(G9V22i33\\{3y32\\[\\%\\%2w\"\"). at /home/kellercl/public_html/runalyze/vendor/symfony/symfony/src/Symfony/Component/Yaml/Unescaper.php:117)"} []

### Apache Log:
	[29-Aug-2016 11:50:37 America/New_York] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'kellercl_runalyz'@'localhost' (using password: YES)' in /runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
	Stack trace:
	#0 /runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'kellercl_runaly...', '9(G9V22i33{3y32...', Array)
	#1 /runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'kellercl_runaly...', '9(G9V22i33{3y32...', Array)
	#2 /runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'kellercl_runaly...', '9(G9V22i33{3y32...', Array)
	#3 /runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection-> in /runalyze/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103

## Unsuccessful approaches
After detecting that there was someting wrong with the password, I tried the following, all with no avail:
* quoting the password using single (`' '`) quotes
* quoting the password using quotation marks (`" "`).
* saving the file in UTF-8 w/out BOM format, also trying various ways of quoting the password as well as escaping **all** non-alphanumeric characters
* saving the file in UTF-8 format, re-trying both of the above as well as not quoting the pwd. This led to an HTTP 500 error on the login page, with apache logging

> PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'There is no extension able to load the configuration for "﻿parameters" (in /runalyze/app/config/../../data/config.yml).

The `data/config.yml` seems to be unreadable in UFT-8 format with BOM.

## Workaround
I had this kind of issue already on another server with a completely different piece of software, so I gave changing the password a try. I changed to password to a rather simple combination of 17 alphanumeric characters - only lower case letters and numbers. **Et violá**: I could login to runalyze again.

Very tricky is the fact that the *shared training log* and *single activites* are accessible while logging is rejected. The error message is kinda misleading since it doesn't tell that there's an authentification error with the database. Anyway, the DB-password seems being handled differently in "frontend" and "backend".

**Comment by mipapo** [comment]
>Very tricky is the fact that the shared training log and single activites are accessible while logging is >rejected. The error message is kinda misleading since it doesn't tell that there's an authentification error >with the database. Anyway, the DB-password seems being handled differently in "frontend" and >"backend".
Like we said - we are still in a migration phase and symfony only uses the database connection for the login. We have two "connections" in the moment. The old database class and the new own. 
We use the yaml parser to parse the values for our old database class and I think this combination makes problem too. 

So I would just say use only letters and numbers and a long password (It's enough for secure password)

**Comment by rob-st** [comment]
Sure, no problem. I thought that's something you should be aware of for further development :-)

**Comment by mipapo** [comment]
I think we should look at the yaml parser we use for the "old database part" of Runalyze.
The problem with your password is the *%%*
If you save it like this
`  database_password: "9(G9V22i33{3y32[%%%%2w"`
It works for Symfony, but our database class will fail

**Comment by laufhannes** [comment]
_(One more time: @mipapo and me writing a comment the same time)_

In theory, complex passwords containing special characters are no problem but they have to be enclosed in quotes. This was not mentioned in our docs properly, but since Runalyze/admin-docs@481f5e5b1f8286183be4fb6b99ceb064d9aef86a it is.

But: I still can't get it working with your special password as the double percent sign seems to cause problems. Using `database_password: '9(G9V22i33{3y32[%2w'` works like a charm (assuming that's the password of the chosen user).

A fast way to check the credentials:
```
$ php bin/console runalyze:install:check
```

Still, the cache has to be cleared each time `config.yml` is changed!
