### ISSUE TITLE
Poster converter failed

### ISSUE THREAD

**Issue by Salzi** [Runalyze/Runalyze#2177]
Try to get the poster generation running on my own installation. Installed all packages but in the end I get the following error in the queue.log

`queue.ERROR: Poster converter failed {"type":"heatmap","exitCode":1} []`

I use the following package versions:

```
  perl_path: /usr/bin/perl
  - v5.20.2
  python3_path: /usr/bin/python3
  - Python 3.4.2
  rsvg_path: /usr/bin/rsvg-convert
  - 2.41.0
  inkscape_path: /usr/bin/inkscape
  - 0.48.5
```

when I run the python script itself with `vendor/runalyze/GpxTrackPoster/create_poster.py`:
```
   vendor/runalyze/GpxTrackPoster/create_poster.py
GPX files: 0
Trying to load 0 track(s) from cache...
('Loaded tracks from cache:', 0)
Merging tracks...
Merged 0 track(s)
Traceback (most recent call last):
  File "vendor/runalyze/GpxTrackPoster/create_poster.py", line 100, in <module>
    main()
  File "vendor/runalyze/GpxTrackPoster/create_poster.py", line 79, in main
    raise Exception('No tracks found.')
Exception: No tracks found.
```

(I had a few missing python packages before)

Did I miss something?

**Comment by mipapo** [comment]
Some posters are just failing sometimes. But it's not clear why. We do not put any effort into this.

**Comment by Salzi** [comment]
Tried a few combinations (different sports, different maps, with/without title, different years) and they all failed :-(

**Comment by mipapo** [comment]
As the output "error" level is too low we cannot help in that case. It's on our list to get more detailed errors from the generator to the logs

**Comment by mipapo** [comment]
Does the folder `data/poster/` exists?

**Comment by laufhannes** [comment]
Can you try to use `mustRun()` instead of `run()` in [src/CoreBundle/Component/Tool/Poster/GeneratePoster.php#L71](https://github.com/Runalyze/Runalyze/blob/support/4.1.x/src/CoreBundle/Component/Tool/Poster/GeneratePoster.php#L71) (and [.../Poster/Converter/InkscapeConverter.php#L32](https://github.com/Runalyze/Runalyze/blob/support/4.1.x/src/CoreBundle/Component/Tool/Poster/Converter/InkscapeConverter.php#L32) and [.../Poster/Converter/RsvgConverter.php#L32](https://github.com/Runalyze/Runalyze/blob/support/4.1.x/src/CoreBundle/Component/Tool/Poster/Converter/RsvgConverter.php#L32))?

That should throw a `ProcessFailedException` that will be catched by [src/CoreBundle/Queue/Receiver/PosterReceiver.php#L133](https://github.com/Runalyze/Runalyze/blob/support/4.1.x/src/CoreBundle/Queue/Receiver/PosterReceiver.php#L133).

**Comment by Salzi** [comment]
@mipapo yes the folder exists:
`drwxrwxrwx  2 www-data www-data 4.0K May 15 21:48 poster
`

@laufhannes do I need to run gulp when changing the php files?

**Comment by mipapo** [comment]
> do I need to run gulp when changing the php files?
no

**Comment by Salzi** [comment]
New log file entry in queue.log
```
[2017-05-17 16:25:48] queue.ERROR: Poster creation failed {"type":"circular","exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"/usr/bin/python3 create_poster.py --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/d2f0700d4c323e8cf04c532d7cfc53f5.svg --type circular --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /var/www/runalyze/app/../vendor/runalyze/GpxTrackPoster/\n\nOutput:\n================\n\n\nError Output:\n================\nTraceback (most recent call last):\n  File \"create_poster.py\", line 10, in <module>\n    import appdirs\nImportError: No module named 'appdirs'\n at /var/www/runalyze/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:233)"} []
[2017-05-17 16:25:48] queue.ERROR: Poster creation failed {"type":"calendar","exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"/usr/bin/python3 create_poster.py --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/d2f0700d4c323e8cf04c532d7cfc53f5.svg --type circular --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73 --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/165360a9a502f3db282a5b0a979117a0.svg --type calendar --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /var/www/runalyze/app/../vendor/runalyze/GpxTrackPoster/\n\nOutput:\n================\n\n\nError Output:\n================\nTraceback (most recent call last):\n  File \"create_poster.py\", line 10, in <module>\n    import appdirs\nImportError: No module named 'appdirs'\n at /var/www/runalyze/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:233)"} []
[2017-05-17 16:25:48] queue.ERROR: Poster creation failed {"type":"grid","exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"/usr/bin/python3 create_poster.py --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/d2f0700d4c323e8cf04c532d7cfc53f5.svg --type circular --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73 --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/165360a9a502f3db282a5b0a979117a0.svg --type calendar --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73 --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/165360a9a502f3db282a5b0a979117a0.svg --type grid --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /var/www/runalyze/app/../vendor/runalyze/GpxTrackPoster/\n\nOutput:\n================\n\n\nError Output:\n================\nTraceback (most recent call last):\n  File \"create_poster.py\", line 10, in <module>\n    import appdirs\nImportError: No module named 'appdirs'\n at /var/www/runalyze/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:233)"} []
[2017-05-17 16:25:48] queue.ERROR: Poster creation failed {"type":"heatmap","exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"/usr/bin/python3 create_poster.py --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/d2f0700d4c323e8cf04c532d7cfc53f5.svg --type circular --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73 --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/165360a9a502f3db282a5b0a979117a0.svg --type calendar --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73 --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/165360a9a502f3db282a5b0a979117a0.svg --type grid --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73 --json-dir /var/www/runalyze/app/../var/tmp/1e2def0a19763fc4c19a701f0898d112 --athlete jonas --year 2016 --output /var/www/runalyze/app/../var/poster/165360a9a502f3db282a5b0a979117a0.svg --type heatmap --title ' ' --stat-num 39 --stat-total 532.08 --stat-min 3.69 --stat-max 24.73\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /var/www/runalyze/app/../vendor/runalyze/GpxTrackPoster/\n\nOutput:\n================\n\n\nError Output:\n================\nTraceback (most recent call last):\n  File \"create_poster.py\", line 10, in <module>\n    import appdirs\nImportError: No module named 'appdirs'\n at /var/www/runalyze/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:233)"} []
```

My mistake was that I installed everything for python 2.7 ... Now I installed all packages for python 3. When I execute the following command `sudo -u www-data php -f /var/www/runalyze/bin/console runalyze:queue:consume --env=prod --max-runtime 120 --max-messages 10 --stop-when-empty` i get the following warnings:

```
PHP Notice:  Object of class Symfony\Component\Process\Process could not be converted to int in /var/www/runalyze/src/CoreBundle/Queue/Receiver/PosterReceiver.php on line 125
PHP Notice:  Object of class Symfony\Component\Process\Process could not be converted to int in /var/www/runalyze/src/CoreBundle/Queue/Receiver/PosterReceiver.php on line 125
PHP Notice:  Object of class Symfony\Component\Process\Process could not be converted to int in /var/www/runalyze/src/CoreBundle/Queue/Receiver/PosterReceiver.php on line 125
PHP Notice:  Object of class Symfony\Component\Process\Process could not be converted to int in /var/www/runalyze/src/CoreBundle/Queue/Receiver/PosterReceiver.php on line 125
```

And the following entry in the queue.log:

```
[2017-05-17 16:31:45] queue.ERROR: Poster converter failed {"type":"circular","exitCode":"[object] (Symfony\\Component\\Process\\Process: {})"} []
[2017-05-17 16:31:46] queue.ERROR: Poster converter failed {"type":"calendar","exitCode":"[object] (Symfony\\Component\\Process\\Process: {})"} []
[2017-05-17 16:31:47] queue.ERROR: Poster converter failed {"type":"grid","exitCode":"[object] (Symfony\\Component\\Process\\Process: {})"} []
[2017-05-17 16:31:50] queue.ERROR: Poster converter failed {"type":"heatmap","exitCode":"[object] (Symfony\\Component\\Process\\Process: {})"} []
```

**Comment by mipapo** [comment]
>  No module named 'appdirs'\
 
There are still missing dependencies https://github.com/laufhannes/GpxTrackPoster/blob/runalyze/requirements.txt
https://docs.runalyze.com/en/latest/installation/4.x.html
> pip3 install -r vendor/runalyze/GpxTrackPoster/requirements.txt
